### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by lildent** [mohamed1234567890vv/PowerBIOptionSetValueToTextConverter#1]
This looks really interesting. have you got any examples on how to use this within powerbi ?

ie when do you call this function in an advanced script in power query ? 

Thanks

Jonathan

**Comment by mohamed1234567890vv** [comment]
Hello @lildent 

Please find attached the document that provides a detailed explanation of the my tool
[Power BI Option Set Value To Text Converter.pdf](https://github.com/mohamed1234567890vv/PowerBIOptionSetValueToTextConverter/files/14528291/Power.BI.Option.Set.Value.To.Text.Converter.pdf)
If you have any questions or need further assistance while going through the documentation, please feel free to reach out to me. I am available to provide any additional information or clarification that you may require.

Thank you for your interest and I hope you find the attached documentation helpful. I look forward to hearing your feedback and assisting you further if needed.

Thank you and best regards,
Mohamed Talaat 
Senior D365 CE Consultant | MCT
